# security properties could be removed, if it's configured in the manifest.yml through environment variable SECURITY_USER_NAME and SECURITY_USER_PASSWORD
security:
    user:
        password: pass
services:  
    TRIPADVISOR:
        NAME: TRIPADVISOR_test_Service2
        DESCRIPTION: My existing service 
        CREDENTIALS:
            URI: http://....
        plans:
            DEFAULT:
              CREDENTIALS:
                 URI: http://....
    API_DIRECTORY:
        NAME: API_DIRECTORY_test_Service2
        DESCRIPTION: My existing service
        METADATA:
            LONG_DESCRIPTION: A long description for my service
        CREDENTIALS:
            HOSTNAME: http://company.com
        plans:
            PLAN1:
                NAME: dev
                CREDENTIALS:
                    URI: http://mydev-api.org
                    ACCESS_KEY: devAZERT23456664DFDSFSDFDSF
            PLAN2:
                NAME: preprod
                CREDENTIALS:
                    URI: http://mypreprod-api.org
                    ACCESS_KEY: preprodAZERT23456664DFDSFSDFDSF
            PLAN3:
                NAME: prod
                CREDENTIALS:
                    URI: http://myprod-api.org
                    ACCESS_KEY: prodAZERT23456664DFDSFSDFDSF
                    HOSTNAME: http://prod.company.com
    ID:
        NAME: static-creds-service-test2
        DESCRIPTION: static-creds service for test
        TAGS: tag1,tag2,tag3
        METADATA:
            DISPLAYNAME: displayname for my service
            IMAGEURL: https://upload.wikimedia.org/wikipedia/commons/c/c8/Orange_logo.svg
            SUPPORTURL: https://github.com/tao-xinxiu/static-creds-broker
            DOCUMENTATIONURL: https://github.com/tao-xinxiu/static-creds-broker
            PROVIDERDISPLAYNAME: provider display name
            LONG_DESCRIPTION: A long description for my service
        plans:
            1:
                NAME: myplan
                DESCRIPTION: The description of the plan
                #METADATA: '{"bullets":["20 GB of messages","20 connections"],"costs":[{"amount":{"usd":99.0,"eur":49.0},"unit":"MONTHLY"},{"amount":{"usd":0.99,"eur":0.49},"unit":"1GB of messages over 20GB"}],"displayName":"Big Bunny"}'
                #FREE: false
        CREDENTIALS_JSON: '{"username":"admin", "password":"pa55woRD", "uri":"mysql://USERNAME:PASSWORD@HOSTNAME:PORT/NAME", "HOSTNAME": "us-cdbr-east-03.cleardb.com"}'
            # uri: mysql://USERNAME:PASSWORD@HOSTNAME:PORT/NAME
            # HOSTNAME: us-cdbr-east-03.cleardb.com