---
applications:
- name: <broker_app_name>
  instances: 1
  memory: 256M
  host: <broker_hostname>
  domain: <my-admin-domain.cf.io>
  path: <binary_jar_exploded_path>

  env:
    # mandatory variables
    SECURITY_USER_PASSWORD: <broker_password>