---
resources:
- name: static-creds-broker  
  type: git  
  source:
    uri: https://github.com/Orange-OpenSource/static-creds-broker.git
    branch: concourse-acceptance-test

jobs:
- name: acceptance-test
  public: true
  plan: 
  - get: static-creds-broker
    trigger: true
  - task: package
    privileged: true
    file: static-creds-broker/concourse/task_package.yml
  - task: acceptance-test    
    file: static-creds-broker/concourse/task_robot_test.yml
    config:
      params:         
        cf_target_endpoint: {{cf_target_endpoint}}        
        skip_ssl_verification: {{skip_ssl_verification}}        
        cf_username: {{cf_username}}        
        cf_password: {{cf_password}}        
        organization_name: {{organization_name}}        
        space_name: {{space_name}}
        broker_app_name: {{broker_app_name}}
        broker_hostname: {{broker_hostname}}
        broker_domain: {{broker_domain}}
        broker_release_version: {{broker_release_version}}
        broker_password: {{broker_password}}
        use_yaml_config: false
        use_remote_config: false
        broker_name: {{broker_name}}
        protocol: {{protocol}}
        test_application_name: {{test_application_name}}
    ensure: 
      task: print_log
      config:
        platform: linux
        image: docker:///busybox
        inputs:
          - name: report
        run:
          path: cat
          args: ["report/output.xml"]